/* eslint-disable */
require('./advice')
require('./baby')
require('./body')
require('./close')
require('./cosmetic-products')
require('./dressing')
require('./error-notif')
require('./eye')
require('./health-products')
require('./info')
require('./medicinal-herb')
require('./orthopedic')
require('./pill')
require('./reload')
require('./success-notif')
